#!/usr/bin/env python3
"""Analyze TYCHOS-minus-JPL residuals for any body (optional lunar diagnostics).

Input must be the CSV generated by compare_ephemerides.py.
The script:
  * selects JPL ICRF astrometric or Earth true-of-date apparent RA/Dec;
  * for ICRF only, converts both datasets to a common J2000 ecliptic frame;
  * computes RA/Dec and angular-separation statistics in either mode;
  * computes longitude/latitude diagnostics only for the fixed ICRF mode;
  * computes annual RMS statistics;
  * fits selected lunar periodicities by least squares;
  * produces an FFT peak list for discovery/diagnostics;
  * writes a machine-readable JSON summary.

Example:
    py scripts/analyze_ephemerides.py \
        data/derived/moon_comparison.csv \
        --body moon --out-dir reports
"""

import argparse
import csv
import json
import math
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np

# Fixed J2000 obliquity is a common diagnostic rotation. The simulator's
# reference-frame accuracy must be evaluated separately.
EPSILON_J2000_DEG = 23.439291111

# Periods are diagnostic fingerprints, not causal assumptions.
KNOWN_COMPONENTS = [
    ("variation", 14.765294),
    ("sidereal_month", 27.321661),
    ("anomalistic_month", 27.554551),
    ("synodic_month", 29.530589),
    ("evection", 31.811938),
    ("annual", 365.256363),
    ("apsidal_precession", 3232.6054),
    ("nodal_regression", 6798.3835),
]

PRIMARY_COMPONENT_NAMES = {
    "variation",
    "anomalistic_month",
    "evection",
    "annual",
}


def wrap_deg(x):
    return (x + 180.0) % 360.0 - 180.0


def rms(a):
    a = np.asarray(a, dtype=float)
    return float(np.sqrt(np.mean(a * a)))


def percentile_abs(a, p):
    return float(np.percentile(np.abs(np.asarray(a, dtype=float)), p))


def stats(a):
    a = np.asarray(a, dtype=float)
    return {
        "mean_deg": float(np.mean(a)),
        "rms_deg": rms(a),
        "median_abs_deg": float(np.median(np.abs(a))),
        "p95_abs_deg": percentile_abs(a, 95),
        "max_abs_deg": float(np.max(np.abs(a))),
    }


def equatorial_to_ecliptic(ra_deg, dec_deg):
    ra = np.radians(np.asarray(ra_deg, dtype=float))
    dec = np.radians(np.asarray(dec_deg, dtype=float))
    eps = math.radians(EPSILON_J2000_DEG)

    x = np.cos(dec) * np.cos(ra)
    y = np.cos(dec) * np.sin(ra)
    z = np.sin(dec)

    xe = x
    ye = y * math.cos(eps) + z * math.sin(eps)
    ze = -y * math.sin(eps) + z * math.cos(eps)

    lon = np.degrees(np.arctan2(ye, xe)) % 360.0
    lat = np.degrees(np.arcsin(np.clip(ze, -1.0, 1.0)))
    return lon, lat


REFERENCE_COLUMNS = {
    "icrf": {
        "ra": "jpl_ra_icrf_deg",
        "dec": "jpl_dec_icrf_deg",
        "ddec": "ddec_icrf_deg",
        "sep": "sep_icrf_deg",
        "label": "JPL ICRF astrometric RA/Dec",
    },
    "apparent-of-date": {
        "ra": "jpl_ra_app_deg",
        "dec": "jpl_dec_app_deg",
        "ddec": "ddec_app_deg",
        "sep": "sep_app_deg",
        "label": "JPL Earth true-equator/equinox-of-date apparent RA/Dec (airless)",
    },
}


def read_comparison(path, reference="icrf"):
    columns = REFERENCE_COLUMNS[reference]
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        required = {
            "date",
            "ty_ra_deg",
            "ty_dec_deg",
            columns["ra"],
            columns["dec"],
            columns["ddec"],
            columns["sep"],
        }
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required columns: {sorted(missing)}")

        for r in reader:
            rows.append({
                "date": datetime.strptime(r["date"], "%Y-%m-%d %H:%M:%S"),
                "ty_ra_deg": float(r["ty_ra_deg"]),
                "ty_dec_deg": float(r["ty_dec_deg"]),
                "jpl_ra_deg": float(r[columns["ra"]]),
                "jpl_dec_deg": float(r[columns["dec"]]),
                "ddec_deg": float(r[columns["ddec"]]),
                "sep_deg": float(r[columns["sep"]]),
            })
    if not rows:
        raise ValueError("No rows found in comparison CSV")
    return rows


def fit_periods(t_days, y_deg, components):
    """Joint least-squares fit: c0 + c1*t + sum A*sin(wt+phase)."""
    t_days = np.asarray(t_days, dtype=float)
    y = np.asarray(y_deg, dtype=float)

    # Center t to reduce conditioning problems for the linear trend.
    tc = t_days - np.mean(t_days)
    cols = [np.ones_like(tc), tc]
    meta = []

    for name, period in components:
        w = 2.0 * np.pi / period
        cols.append(np.sin(w * t_days))
        cols.append(np.cos(w * t_days))
        meta.append((name, period, len(cols) - 2, len(cols) - 1))

    X = np.column_stack(cols)
    coef, *_ = np.linalg.lstsq(X, y, rcond=None)
    model = X @ coef
    residual = y - model

    results = []
    for name, period, i_sin, i_cos in meta:
        a = float(coef[i_sin])
        b = float(coef[i_cos])
        amp = math.hypot(a, b)
        # y = A sin(w t + phi) => a=A cos(phi), b=A sin(phi)
        phase = math.degrees(math.atan2(b, a))
        results.append({
            "name": name,
            "period_days": period,
            "amplitude_deg": amp,
            "phase_deg_at_t0": phase,
            "sin_coeff": a,
            "cos_coeff": b,
        })

    return results, model, residual, float(coef[0]), float(coef[1])


def fft_peaks(t_days, y_deg, min_period=1.0, max_period=500.0, n_peaks=20):
    t = np.asarray(t_days, dtype=float)
    y = np.asarray(y_deg, dtype=float)
    if len(t) < 8:
        return []

    dt = np.diff(t)
    step = float(np.median(dt))
    if np.max(np.abs(dt - step)) > max(1e-9, step * 1e-5):
        return []

    # Remove constant + linear trend before FFT.
    tc = t - np.mean(t)
    X = np.column_stack([np.ones_like(tc), tc])
    coef, *_ = np.linalg.lstsq(X, y, rcond=None)
    detrended = y - X @ coef

    window = np.hanning(len(y))
    yw = detrended * window
    spec = np.fft.rfft(yw)
    freq = np.fft.rfftfreq(len(y), d=step)
    amp = 2.0 * np.abs(spec) / np.sum(window)

    peaks = []
    for i in range(1, len(freq)):
        if freq[i] <= 0:
            continue
        period = 1.0 / freq[i]
        if min_period <= period <= max_period:
            peaks.append((float(amp[i]), float(period), float(freq[i])))

    peaks.sort(reverse=True)

    # Avoid returning adjacent FFT bins representing the same broad peak.
    selected = []
    for amplitude, period, frequency in peaks:
        if any(abs(period - p["period_days"]) / period < 0.01 for p in selected):
            continue
        selected.append({
            "period_days": period,
            "amplitude_deg": amplitude,
            "frequency_cycles_per_day": frequency,
        })
        if len(selected) >= n_peaks:
            break
    return selected


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("comparison_csv")
    parser.add_argument("--out-dir", default="reports")
    parser.add_argument("--body", required=True)
    parser.add_argument("--profile", choices=("auto", "none", "lunar"), default="auto")
    parser.add_argument("--prefix", help="Output prefix; defaults to body")
    parser.add_argument(
        "--reference",
        choices=tuple(REFERENCE_COLUMNS),
        default="icrf",
        help="JPL coordinate product to analyze (default: icrf)",
    )
    args = parser.parse_args(argv)
    if not re.fullmatch(r"[a-z][a-z0-9_]*", args.body):
        parser.error("Body must be a lowercase identifier")
    prefix = args.prefix or args.body
    if not re.fullmatch(r"[a-z][a-z0-9_]*", prefix):
        parser.error("Prefix must be a lowercase identifier")
    lunar_requested = args.profile == "lunar" or (args.profile == "auto" and args.body == "moon")
    if args.profile == "lunar" and args.reference != "icrf":
        parser.error("Lunar longitude diagnostics require --reference icrf")
    lunar = lunar_requested and args.reference == "icrf"
    if lunar and args.body != "moon":
        parser.error("Lunar diagnostics are only supported for moon")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = read_comparison(args.comparison_csv, args.reference)
    dates = [r["date"] for r in rows]
    if dates != sorted(set(dates)):
        raise ValueError("Comparison dates must be unique and increasing")
    if not all(math.isfinite(v) for row in rows for k, v in row.items() if k != "date"):
        raise ValueError("Comparison contains non-finite coordinates")
    t0 = dates[0]
    t_days = np.array([(d - t0).total_seconds() / 86400.0 for d in dates])

    ty_ra = np.array([r["ty_ra_deg"] for r in rows])
    ty_dec = np.array([r["ty_dec_deg"] for r in rows])
    jp_ra = np.array([r["jpl_ra_deg"] for r in rows])
    jp_dec = np.array([r["jpl_dec_deg"] for r in rows])
    dra = np.array([wrap_deg(v) for v in (ty_ra - jp_ra)])
    ddec = np.array([r["ddec_deg"] for r in rows])
    sep = np.array([r["sep_deg"] for r in rows])

    ecliptic_enabled = args.reference == "icrf"
    if ecliptic_enabled:
        ty_lon, ty_lat = equatorial_to_ecliptic(ty_ra, ty_dec)
        jp_lon, jp_lat = equatorial_to_ecliptic(jp_ra, jp_dec)
        dlon = np.array([wrap_deg(v) for v in (ty_lon - jp_lon)])
        dlat = ty_lat - jp_lat

    fft_values = dlon if ecliptic_enabled else dra
    fft_observable = "ecliptic longitude residual" if ecliptic_enabled else "right ascension residual"

    cadence_hours = None
    if len(dates) > 1:
        cadence_hours = float(np.median(np.diff(t_days)) * 24.0)

    if lunar:
        # Primary four-component fit used for the compact residual result.
        primary_components = [c for c in KNOWN_COMPONENTS if c[0] in PRIMARY_COMPONENT_NAMES]
        primary_fit, primary_model, primary_residual, primary_offset, primary_trend = fit_periods(
            t_days, dlon, primary_components
        )

        # Full diagnostic fit includes longer and neighboring lunar periods.
        full_fit, full_model, full_residual, full_offset, full_trend = fit_periods(
            t_days, dlon, KNOWN_COMPONENTS
        )

        var_before = float(np.var(dlon))
        var_after_primary = float(np.var(primary_residual))
        explained_primary = 100.0 * (1.0 - var_after_primary / var_before) if var_before else 0.0

    summary = {
        "body": args.body,
        "profile": "lunar" if lunar else "none",
        "input_file": str(args.comparison_csv),
        "reference_mode": args.reference,
        "reference": REFERENCE_COLUMNS[args.reference]["label"],
        "ecliptic_rotation": (
            f"fixed J2000 obliquity {EPSILON_J2000_DEG} deg"
            if ecliptic_enabled
            else "Not computed: true-of-date RA/Dec must not be rotated with fixed J2000 obliquity"
        ),
        "n_samples": len(rows),
        "start": dates[0].strftime("%Y-%m-%d %H:%M:%S"),
        "stop": dates[-1].strftime("%Y-%m-%d %H:%M:%S"),
        "cadence_hours_median": cadence_hours,
        "cadence_regular": bool(len(t_days) < 2 or np.allclose(np.diff(t_days), np.diff(t_days)[0], rtol=0, atol=1e-9)),
        "fft_period_range_days": [1.0, 500.0],
        "fft_observable": fft_observable,
        "ra_residual": stats(dra),
        "declination_residual": stats(ddec),
        "angular_separation": stats(sep),
    }
    if ecliptic_enabled:
        summary.update({
            "ecliptic_longitude_residual": stats(dlon),
            "ecliptic_latitude_residual": stats(dlat),
        })
    if lunar:
        summary.update({
            "primary_period_fit": {
                "periods": [name for name, _ in primary_components],
                "rms_before_deg": rms(dlon),
                "rms_after_deg": rms(primary_residual),
                "variance_explained_percent": explained_primary,
                "offset_deg": primary_offset,
                "linear_trend_deg_per_day": primary_trend,
            },
            "full_period_fit": {
                "rms_after_deg": rms(full_residual),
                "offset_deg": full_offset,
                "linear_trend_deg_per_day": full_trend,
            },
        })

    with (out_dir / f"{prefix}_summary.json").open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    if lunar:
        # Periodic component table: primary and full-fit values side by side.
        primary_by_name = {r["name"]: r for r in primary_fit}
        full_by_name = {r["name"]: r for r in full_fit}
        with (out_dir / f"{prefix}_periodic_components.csv").open("w", newline="", encoding="utf-8") as f:
            fields = [
                "name", "period_days", "primary_amplitude_deg", "primary_phase_deg",
                "full_fit_amplitude_deg", "full_fit_phase_deg"
            ]
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
            for name, period in KNOWN_COMPONENTS:
                p = primary_by_name.get(name)
                q = full_by_name.get(name)
                w.writerow({
                    "name": name,
                    "period_days": period,
                    "primary_amplitude_deg": "" if p is None else p["amplitude_deg"],
                    "primary_phase_deg": "" if p is None else p["phase_deg_at_t0"],
                    "full_fit_amplitude_deg": "" if q is None else q["amplitude_deg"],
                    "full_fit_phase_deg": "" if q is None else q["phase_deg_at_t0"],
                })

    # FFT discovery table.
    peaks = fft_peaks(t_days, fft_values)
    with (out_dir / f"{prefix}_fft_peaks.csv").open("w", newline="", encoding="utf-8") as f:
        fields = ["rank", "period_days", "amplitude_deg", "frequency_cycles_per_day"]
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for i, p in enumerate(peaks, 1):
            w.writerow({"rank": i, **p})

    # Annual summary.
    years = defaultdict(list)
    for i, d in enumerate(dates):
        years[d.year].append(i)

    with (out_dir / f"{prefix}_annual_stats.csv").open("w", newline="", encoding="utf-8") as f:
        fields = (
            ["year", "n", "rms_dlon_deg", "rms_dlat_deg", "rms_ddec_deg", "rms_sep_deg"]
            if ecliptic_enabled
            else ["year", "n", "rms_dra_deg", "rms_ddec_deg", "rms_sep_deg"]
        )
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for year in sorted(years):
            idx = np.array(years[year], dtype=int)
            row = {
                "year": year,
                "n": len(idx),
                "rms_ddec_deg": rms(ddec[idx]),
                "rms_sep_deg": rms(sep[idx]),
            }
            if ecliptic_enabled:
                row.update({
                    "rms_dlon_deg": rms(dlon[idx]),
                    "rms_dlat_deg": rms(dlat[idx]),
                })
            else:
                row["rms_dra_deg"] = rms(dra[idx])
            w.writerow(row)

    # Row-level residual file for follow-up plots or external checks.
    with (out_dir / f"{prefix}_residuals.csv").open("w", newline="", encoding="utf-8") as f:
        fields = (
            ["date", "ty_ecl_lon_deg", "ty_ecl_lat_deg", "jpl_ecl_lon_deg", "jpl_ecl_lat_deg",
             "dlon_deg", "dlat_deg", "ddec_deg", "sep_deg"]
            if ecliptic_enabled
            else ["date", "ty_ra_deg", "ty_dec_deg", "jpl_ra_deg", "jpl_dec_deg",
                  "dra_deg", "ddec_deg", "sep_deg"]
        )
        if lunar:
            fields.extend(["primary_model_dlon_deg", "primary_residual_dlon_deg"])
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for i, d in enumerate(dates):
            if ecliptic_enabled:
                row = {
                    "date": d.strftime("%Y-%m-%d %H:%M:%S"),
                    "ty_ecl_lon_deg": ty_lon[i],
                    "ty_ecl_lat_deg": ty_lat[i],
                    "jpl_ecl_lon_deg": jp_lon[i],
                    "jpl_ecl_lat_deg": jp_lat[i],
                    "dlon_deg": dlon[i],
                    "dlat_deg": dlat[i],
                    "ddec_deg": ddec[i],
                    "sep_deg": sep[i],
                    **({"primary_model_dlon_deg": primary_model[i],
                        "primary_residual_dlon_deg": primary_residual[i]} if lunar else {}),
                }
            else:
                row = {
                    "date": d.strftime("%Y-%m-%d %H:%M:%S"),
                    "ty_ra_deg": ty_ra[i],
                    "ty_dec_deg": ty_dec[i],
                    "jpl_ra_deg": jp_ra[i],
                    "jpl_dec_deg": jp_dec[i],
                    "dra_deg": dra[i],
                    "ddec_deg": ddec[i],
                    "sep_deg": sep[i],
                }
            w.writerow(row)

    print(f"Samples: {len(rows)}")
    print(f"Interval: {dates[0]} -> {dates[-1]}")
    print(f"Median cadence: {cadence_hours:.3f} h" if cadence_hours is not None else "Median cadence: n/a")
    print(f"Reference     : {REFERENCE_COLUMNS[args.reference]['label']}")
    if ecliptic_enabled:
        print(f"Longitude RMS: {rms(dlon):.6f} deg")
        print(f"Latitude RMS : {rms(dlat):.6f} deg")
    else:
        print(f"RA RMS        : {rms(dra):.6f} deg")
    print(f"Dec RMS      : {rms(ddec):.6f} deg")
    print(f"Separation RMS: {rms(sep):.6f} deg")
    if lunar:
        print(f"Primary 4-period longitude residual RMS: {rms(primary_residual):.6f} deg")
        print(f"Variance explained by primary fit: {explained_primary:.3f}%")
    print(f"Reports written to: {out_dir}")


if __name__ == "__main__":
    main()
